-- Schema for exam_answers table and topic-tagged resources
-- Run this in Oracle FREEPDB1 as SYSTEM user

-- 1. Create EXAM_ANSWERS table to store per-question student answers
CREATE TABLE exam_answers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(id),
    skill_id NUMBER NOT NULL REFERENCES skills(id),
    question_id NUMBER NOT NULL REFERENCES questions(id),
    selected_option CHAR(1),
    is_correct NUMBER(1) DEFAULT 0,
    answered_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 2. Insert faculty user
INSERT INTO users (username, password, role, full_name, department)
VALUES ('faculty@anurag.edu.in', 'faculty@123', 'faculty', 'Faculty Admin', 'CSE');

-- 3. Add topic_tag column to resources table
ALTER TABLE resources ADD topic_tag VARCHAR2(100);

-- 4. Insert topic-tagged learning resources for Web Development
-- HTML resources
INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (3, 'HTML Basics - W3Schools', 'https://www.w3schools.com/html/', 'Tutorial', 'HTML');

INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (3, 'HTML Tutorial - MDN', 'https://developer.mozilla.org/en-US/docs/Learn/HTML', 'Documentation', 'HTML');

-- CSS resources
INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (3, 'CSS Basics - W3Schools', 'https://www.w3schools.com/css/', 'Tutorial', 'CSS');

INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (3, 'CSS Tutorial - MDN', 'https://developer.mozilla.org/en-US/docs/Learn/CSS', 'Documentation', 'CSS');

INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (3, 'CSS Flexbox Guide', 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/', 'Tutorial', 'CSS');

-- JavaScript resources
INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (3, 'JavaScript Basics - W3Schools', 'https://www.w3schools.com/js/', 'Tutorial', 'JavaScript');

INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (3, 'JavaScript Tutorial - MDN', 'https://developer.mozilla.org/en-US/docs/Learn/JavaScript', 'Documentation', 'JavaScript');

INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (3, 'JavaScript.info - Modern JS', 'https://javascript.info/', 'Tutorial', 'JavaScript');

-- DOM resources
INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (3, 'DOM Manipulation - MDN', 'https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model', 'Documentation', 'DOM');

INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (3, 'DOM Tutorial - W3Schools', 'https://www.w3schools.com/js/js_htmldom.asp', 'Tutorial', 'DOM');

-- General Web Development
INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (3, 'FreeCodeCamp - Full Web Dev', 'https://www.freecodecamp.org/learn', 'Free Course', 'General');

INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (3, 'The Odin Project', 'https://www.theodinproject.com/', 'Free Course', 'General');

-- Java resources (skill_id=1)
INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (1, 'Java OOP - W3Schools', 'https://www.w3schools.com/java/java_oop.asp', 'Tutorial', 'OOP');

INSERT INTO resources (skill_id, title, resource_url, resource_type, topic_tag)
VALUES (1, 'Java Basics - Oracle Docs', 'https://docs.oracle.com/javase/tutorial/', 'Documentation', 'Java');

COMMIT;
