-- Oracle SQL Script for Dynamic Questions
-- Run this in your SQL environment to set up the questions table for the dynamic assessment.

-- 1. Create the QUESTIONS table
CREATE TABLE questions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id NUMBER NOT NULL REFERENCES skills(id),
    question_text VARCHAR2(1000) NOT NULL,
    option_a VARCHAR2(500) NOT NULL,
    option_b VARCHAR2(500) NOT NULL,
    option_c VARCHAR2(500) NOT NULL,
    option_d VARCHAR2(500) NOT NULL,
    correct_option CHAR(1) NOT NULL CHECK (correct_option IN ('A', 'B', 'C', 'D')),
    difficulty_level NUMBER(1) DEFAULT 1
);

-- 2. Insert sample questions for 'Web Development' (Assuming skill_id = 3 based on schema.sql)
INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'What does HTML stand for?', 'Hyper Text Markup Language', 'High Tech Modern Language', 'Home Tool Markup Language', 'Hyperlinks and Text Markup Language', 'A');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Which programming language is known for web development?', 'Python', 'Java', 'JavaScript', 'C++', 'C');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'What is the primary purpose of CSS?', 'Database management', 'Styling web pages', 'Server-side programming', 'Data validation', 'B');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'What does DOM stand for?', 'Data Object Model', 'Document Oriented Model', 'Document Object Model', 'Data Oriented Model', 'C');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Which HTML tag is used for the largest heading?', '<heading>', '<h6>', '<head>', '<h1>', 'D');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Which attribute specifies the unique identity of an element?', 'class', 'id', 'name', 'type', 'B');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'What does CSS stand for?', 'Computer Style Sheets', 'Creative Style Sheets', 'Cascading Style Sheets', 'Colorful Style Sheets', 'C');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Where in an HTML document is the correct place to refer to an external style sheet?', 'At the end of the document', 'In the <head> section', 'In the <body> section', 'Before the <html> tag', 'B');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Which HTML tag is used to define an internal style sheet?', '<style>', '<css>', '<script>', '<link>', 'A');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Inside which HTML element do we put the JavaScript?', '<javascript>', '<scripting>', '<script>', '<js>', 'C');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'What is the correct JavaScript syntax to change the content of the HTML element <p id="demo">This is a demonstration.</p>?', 'document.getElementById("demo").innerHTML = "Hello World!";', 'document.getElementByName("p").innerHTML = "Hello World!";', '#demo.innerHTML = "Hello World!";', 'document.getElement("p").innerHTML = "Hello World!";', 'A');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'How do you write "Hello World" in an alert box?', 'msgBox("Hello World");', 'alert("Hello World");', 'msg("Hello World");', 'alertBox("Hello World");', 'B');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'How do you create a function in JavaScript?', 'function:myFunction()', 'function = myFunction()', 'function myFunction()', 'create myFunction()', 'C');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'How to write an IF statement in JavaScript?', 'if i = 5 then', 'if i == 5 then', 'if (i == 5)', 'if i = 5', 'C');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'How does a FOR loop start?', 'for (i = 0; i <= 5; i++)', 'for (i <= 5; i++)', 'for i = 1 to 5', 'for (i = 0; i <= 5)', 'A');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Which property is used to change the background color?', 'bgcolor', 'color', 'background-color', 'bgColor', 'C');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'How do you add a comment in a CSS file?', '// this is a comment', '/* this is a comment */', '<!-- this is a comment -->', '" this is a comment', 'B');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Which CSS property is used to set the text color?', 'text-color', 'fgcolor', 'color', 'font-color', 'C');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Which CSS property controls the text size?', 'font-size', 'text-style', 'font-style', 'text-size', 'A');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'How do you display hyperlinks without an underline?', 'a {underline:none;}', 'a {text-decoration:none;}', 'a {decoration:no-underline;}', 'a {text-decoration:no-underline;}', 'B');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'How do you make each word in a text start with a capital letter?', 'text-style:capitalize', 'text-transform:capitalize', 'transform:capitalize', 'text-transform:uppercase', 'B');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Which CSS property controls how an element is positioned?', 'static', 'position', 'display', 'set', 'B');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'What is the default value of the position property?', 'fixed', 'absolute', 'relative', 'static', 'D');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'How do you declare a variable in JavaScript?', 'var carName;', 'variable carName;', 'v carName;', 'string carName;', 'A');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Which operator is used to assign a value to a variable?', '*', '-', '=', 'x', 'C');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'What will the following code return: Boolean(10 > 9)', 'false', 'true', 'NaN', 'undefined', 'B');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Is JavaScript case-sensitive?', 'Yes', 'No', 'Only when using strict mode', 'Only in variable names', 'A');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Which event occurs when the user clicks on an HTML element?', 'onmouseclick', 'onchange', 'onclick', 'onmouseover', 'C');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'What tag is used for creating a hyperlink?', '<a>', '<link>', '<href>', '<hyperlink>', 'A');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(3, 'Which JavaScript method is used to write HTML output?', 'document.write()', 'console.log()', 'document.output()', 'window.print()', 'A');

-- 3. Insert sample questions for 'Java Programming' (skill_id = 1)
INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(1, 'In Java, what does OOP stand for?', 'Object Oriented Programming', 'Open Online Platform', 'Operating Output Process', 'Optimal Object Pattern', 'A');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(1, 'Which concept refers to wrapping data and code as a single unit?', 'Polymorphism', 'Encapsulation', 'Inheritance', 'Abstraction', 'B');

INSERT INTO questions (skill_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES 
(1, 'What is the size of an int variable in Java?', '8 bit', '16 bit', '32 bit', '64 bit', 'C');

-- 4. Commit changes
COMMIT;
